# Generated by Django 5.2 on 2025-04-29 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeakageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='leak_reports/')),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('residential_usage', models.FloatField(default=0.0, help_text='Water usage in liters for residential areas')),
                ('commercial_usage', models.FloatField(default=0.0, help_text='Water usage in liters for commercial areas')),
                ('industrial_usage', models.FloatField(default=0.0, help_text='Water usage in liters for industrial areas')),
            ],
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.FloatField(help_text='Maximum capacity in liters')),
                ('type', models.CharField(choices=[('River', 'River'), ('Reservoir', 'Reservoir'), ('Borewell', 'Borewell'), ('Lake', 'Lake')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Under Maintenance', 'Under Maintenance')], default='Active', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterQualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ph_level', models.FloatField(help_text='PH level of the water')),
                ('contaminants_detected', models.TextField(blank=True, help_text='List of contaminants detected', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or comments', null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_management.watersource')),
            ],
        ),
    ]
