# Generated by Django 5.2 on 2025-04-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leakagereport',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='leakagereport',
            name='longitude',
            field=models.FloatField(default=None),
        ),
    ]
