# Generated by Django 5.2 on 2025-04-29 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=20)),
                ('total_waste_kg', models.FloatField()),
                ('collection_efficiency', models.FloatField(help_text='Percentage of scheduled bins collected')),
                ('complaints_resolved', models.IntegerField()),
                ('complaints_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WasteBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=100)),
                ('bin_type', models.CharField(choices=[('Recyclable', 'Recyclable'), ('Non-Recyclable', 'Non-Recyclable')], max_length=20)),
                ('capacity_kg', models.FloatField(help_text='Maximum bin capacity in kilograms')),
                ('current_fill_kg', models.FloatField(default=0.0)),
                ('last_collected', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WasteTypeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('recyclable_weight', models.FloatField(default=0.0)),
                ('non_recyclable_weight', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('collected', models.BooleanField(default=False)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_management.wastebin')),
            ],
        ),
        migrations.CreateModel(
            name='BinSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_percentage', models.IntegerField(help_text='e.g., 75 means 75% full')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_management.wastebin')),
            ],
        ),
        migrations.CreateModel(
            name='WasteComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='waste_complaints/')),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
