from django.urls import path
from . import views
app_name = 'electricity'

urlpatterns = [
    path('',views.index,name='index'),
    path('grids/', views.grid_list, name='grid_list'),
    path('grids/new/', views.grid_create, name='grid_create'),
    path('grids/<int:pk>/edit/', views.grid_update, name='grid_update'),
    path('grids/<int:pk>/delete/', views.grid_delete, name='grid_delete'),
     path('substations/', views.substation_list, name='substation_list'),
    path('substations/new/', views.substation_create, name='substation_create'),
    path('substations/<int:pk>/edit/', views.substation_update, name='substation_update'),
    path('substations/<int:pk>/delete/', views.substation_delete, name='substation_delete'),
    path('transformers/', views.transformer_list, name='transformer_list'),
    path('transformers/new/', views.transformer_create, name='transformer_create'),
    path('transformers/<int:pk>/edit/', views.transformer_update, name='transformer_update'),
    path('transformers/<int:pk>/delete/', views.transformer_delete, name='transformer_delete'),
    path('consumers/', views.consumer_list, name='consumer_list'),
    path('consumers/<int:pk>/', views.consumer_detail, name='consumer_detail'),
    path('consumers/new/', views.consumer_create, name='consumer_create'),
    path('consumers/<int:pk>/edit/', views.consumer_update, name='consumer_update'),
    path('consumers/<int:pk>/delete/', views.consumer_delete, name='consumer_delete'),
    path('electricity_usages/', views.electricity_usage_list, name='electricity_usage_list'),
    path('electricity_usages/<int:pk>/', views.electricity_usage_detail, name='electricity_usage_detail'),
    path('electricity_usages/new/', views.electricity_usage_create, name='electricity_usage_create'),
    path('electricity_usages/<int:pk>/edit/', views.electricity_usage_update, name='electricity_usage_update'),
    path('electricity_usages/<int:pk>/delete/', views.electricity_usage_delete, name='electricity_usage_delete'),
    path('bills/', views.bill_list, name='bill_list'),
    path('bills/<int:pk>/', views.bill_detail, name='bill_detail'),
    path('bills/new/', views.bill_create, name='bill_create'),
    path('bills/<int:pk>/edit/', views.bill_update, name='bill_update'),
    path('bills/<int:pk>/delete/', views.bill_delete, name='bill_delete'),
    path('create/<int:bill_id>/', views.create_payment, name='create_payment'),
    path('list/', views.payment_list, name='payment_list'),
    path('update/<int:payment_id>/', views.update_payment, name='update_payment'),
    path('delete/<int:payment_id>/', views.delete_payment, name='delete_payment'),
    path('create/', views.create_outage_report, name='create_outage_report'),
    path('outage/', views.outage_report_list, name='outage_report_list'),
    path('<int:pk>/update/', views.update_outage_report, name='update_outage_report'),
    path('<int:pk>/delete/', views.delete_outage_report, name='delete_outage_report'),
     path('outage/<int:outage_id>/feedback/', views.outage_feedback, name='outage_feedback'),
    path('my-outage-reports/', views.my_outage_reports, name='my_outage_reports'),
]
