# Generated by Django 5.2 on 2025-04-29 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('capacity_mw', models.FloatField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('meter_number', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_units', models.FloatField()),
                ('amount_due', models.FloatField()),
                ('is_paid', models.BooleanField(default=False)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity.consumer')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('units_consumed', models.FloatField(help_text='In kWh')),
                ('cost', models.FloatField()),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity.consumer')),
            ],
        ),
        migrations.CreateModel(
            name='OutageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.FloatField()),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('UPI', 'UPI'), ('Cash', 'Cash'), ('Online Banking', 'Online Banking')], max_length=50)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='electricity.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('capacity_mw', models.FloatField()),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity.grid')),
            ],
        ),
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('capacity_kva', models.FloatField()),
                ('status', models.CharField(choices=[('Operational', 'Operational'), ('Faulty', 'Faulty')], max_length=50)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity.substation')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('technician_name', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity.transformer')),
            ],
        ),
        migrations.AddField(
            model_name='consumer',
            name='connected_transformer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='electricity.transformer'),
        ),
    ]
