# Generated by Django 5.2 on 2025-04-30 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0002_outagereport_latitude_outagereport_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outagereport',
            name='feedback_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outagereport',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outagereport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OutageFeedbackNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_provided', models.BooleanField(default=False)),
                ('issue_resolved', models.BooleanField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('outage_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='electricity.outagereport')),
            ],
        ),
    ]
