# Generated by Django 5.2 on 2025-04-29 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('road_type', models.CharField(choices=[('Highway', 'Highway'), ('Street', 'Street'), ('Alley', 'Alley'), ('Avenue', 'Avenue')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('condition', models.CharField(default='Good', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('description', models.TextField()),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road.road')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('Accident', 'Accident'), ('Roadwork', 'Roadwork'), ('Obstacle', 'Obstacle')], max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Minor', 'Minor'), ('Major', 'Major')], max_length=20)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road.road')),
            ],
        ),
    ]
