# Generated by Django 5.2 on 2025-04-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficincident',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
