# Generated by Django 5.2 on 2025-04-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0002_trafficincident_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficincident',
            name='latitude',
            field=models.FloatField(default=12321243),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficincident',
            name='longitude',
            field=models.FloatField(default=1232143223),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='road',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='road',
            name='longitude',
            field=models.FloatField(default=None),
        ),
    ]
