# Generated by Django 5.2 on 2025-04-29 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0003_trafficincident_latitude_trafficincident_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficincident',
            name='user',
            field=models.ForeignKey(default=123424212, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trafficincident',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='trafficincident',
            name='longitude',
            field=models.FloatField(default=None),
        ),
    ]
