# Generated by Django 5.2 on 2025-04-29 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0005_alter_trafficincident_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficincident',
            name='user',
        ),
    ]
