# Generated by Django 5.2 on 2025-04-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0007_trafficincident_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficincident',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trafficincident',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
